FROM python:3.8.3-slim
WORKDIR /scripts
COPY ./train/src/scripts ./train/src/scripts
COPY ./train/src/data ./train/data

RUN apt-get update \
    && apt-get -y install cron \
    && apt-get -y install libpq-dev gcc \
    && python -m pip install -r requirements.txt

CMD [ "./run.sh" ]
